/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caoym_ezsync_Client */

#ifndef _Included_com_caoym_ezsync_Client
#define _Included_com_caoym_ezsync_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caoym_ezsync_Client
 * Method:    commit
 * Signature: (Ljava/lang/String;)[Lcom/caoym/ezsync/Changed;
 */
JNIEXPORT jobjectArray JNICALL Java_com_caoym_ezsync_Client_commit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_caoym_ezsync_Client
 * Method:    delete
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_Client_delete
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_caoym_ezsync_Client
 * Method:    update
 * Signature: (Lcom/caoym/ezsync/MergeStrategy;Ljava/lang/String;Ljava/lang/String;Lcom/caoym/ezsync/UpdateListener;)[Lcom/caoym/ezsync/Changed;
 */
JNIEXPORT jobjectArray JNICALL Java_com_caoym_ezsync_Client_update
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject);

/*
 * Class:     com_caoym_ezsync_Client
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_Client_cancel
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_ezsync_Client
 * Method:    upgradeLocalStorage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_Client_upgradeLocalStorage
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_ezsync_Client
 * Method:    destroyJniObj
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_Client_destroyJniObj
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_ezsync_Client
 * Method:    createJniObj
 * Signature: (Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_Client_createJniObj
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
