/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caoym_ezsync_AppSetting */

#ifndef _Included_com_caoym_ezsync_AppSetting
#define _Included_com_caoym_ezsync_AppSetting
#ifdef __cplusplus
extern "C" {
#endif
#undef com_caoym_ezsync_AppSetting_DEBUG
#define com_caoym_ezsync_AppSetting_DEBUG 0L
#undef com_caoym_ezsync_AppSetting_INFO
#define com_caoym_ezsync_AppSetting_INFO 1L
#undef com_caoym_ezsync_AppSetting_WARN
#define com_caoym_ezsync_AppSetting_WARN 2L
#undef com_caoym_ezsync_AppSetting_ERROR
#define com_caoym_ezsync_AppSetting_ERROR 4L
#undef com_caoym_ezsync_AppSetting_ALL
#define com_caoym_ezsync_AppSetting_ALL -1L
#undef com_caoym_ezsync_AppSetting_RELEASE
#define com_caoym_ezsync_AppSetting_RELEASE 7L
/*
 * Class:     com_caoym_ezsync_AppSetting
 * Method:    enableLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_AppSetting_enableLog
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_caoym_ezsync_AppSetting
 * Method:    disableLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_ezsync_AppSetting_disableLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
